# Generated by Django 5.2.6 on 2025-09-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Muda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(max_length=100)),
                ('quantidade', models.PositiveIntegerField()),
                ('local', models.CharField(max_length=150)),
                ('responsavel', models.CharField(max_length=100)),
                ('data_plantio', models.DateField()),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='mudas/')),
            ],
        ),
    ]
