# Generated by Django 5.2.6 on 2025-10-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reflorestamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(max_length=70)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='animais/')),
                ('origem', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPlanta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=70)),
                ('adubo', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Vegetacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=70)),
            ],
        ),
    ]
