# Generated by Django 5.2 on 2025-10-26 18:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reflorestamento', '0002_animal_tipoplanta_vegetacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoplanta',
            name='hora',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
