# Generated by Django 5.2.6 on 2025-09-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('problema', models.CharField(choices=[('desmatamento', 'Desmatamento'), ('queimada', 'Queimada'), ('seca', 'Seca')], max_length=20)),
                ('status', models.CharField(choices=[('critico', 'Crítico'), ('recuperacao', 'Em Recuperação'), ('estavel', 'Estável')], default='critico', max_length=20)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='areas/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
