# Generated by Django 5.2 on 2025-10-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='posts/videos/'),
        ),
        migrations.AddField(
            model_name='post',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='posts/imagens/'),
        ),
    ]
